// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BgZxhKhfJDKad0I1-FZalNdyDXVpGR0',
    appId: '1:928778853273:web:a3e0456753f576e1089108',
    messagingSenderId: '928778853273',
    projectId: 'flutter-auth-18ed2',
    authDomain: 'flutter-auth-18ed2.firebaseapp.com',
    databaseURL: 'https://flutter-auth-18ed2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-auth-18ed2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWRq0e7OFj342ysKO8QkMWp61KnqcHAs8',
    appId: '1:928778853273:android:8ad554487394a785089108',
    messagingSenderId: '928778853273',
    projectId: 'flutter-auth-18ed2',
    databaseURL: 'https://flutter-auth-18ed2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-auth-18ed2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7BgZxhKhfJDKad0I1-FZalNdyDXVpGR0',
    appId: '1:928778853273:web:654286692878aae0089108',
    messagingSenderId: '928778853273',
    projectId: 'flutter-auth-18ed2',
    authDomain: 'flutter-auth-18ed2.firebaseapp.com',
    databaseURL: 'https://flutter-auth-18ed2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-auth-18ed2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3RZWGNf62-uc0Y8YhR48vrIRSf-MJ0WA',
    appId: '1:928778853273:ios:ac96c8bc4739a949089108',
    messagingSenderId: '928778853273',
    projectId: 'flutter-auth-18ed2',
    databaseURL: 'https://flutter-auth-18ed2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-auth-18ed2.firebasestorage.app',
    androidClientId: '928778853273-lvm3ur6r14u47ggg9lgis2gfpspubq83.apps.googleusercontent.com',
    iosClientId: '928778853273-vo9ta8jrh6auufnoqkvfojsaur2r524f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3RZWGNf62-uc0Y8YhR48vrIRSf-MJ0WA',
    appId: '1:928778853273:ios:ac96c8bc4739a949089108',
    messagingSenderId: '928778853273',
    projectId: 'flutter-auth-18ed2',
    databaseURL: 'https://flutter-auth-18ed2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-auth-18ed2.firebasestorage.app',
    androidClientId: '928778853273-lvm3ur6r14u47ggg9lgis2gfpspubq83.apps.googleusercontent.com',
    iosClientId: '928778853273-vo9ta8jrh6auufnoqkvfojsaur2r524f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

}